### ISSUE TITLE
PC and NPC creation

### ISSUE THREAD

**Issue by RGK13** [jalensailin/mvrpg#1]
When creating a new actor you do not get a choice for an NPC or a PC. Maybe also adding vehicle actor would be nice.

**Comment by jalensailin** [comment]
As far as I can tell, there is no difference between the character sheets for PCs and NPCs, hence why there is no choice on character creation.

I can see why it would still be helpful to distinguish between the two, though, for organization purposes and macros, to name a few.

As far as vehicles go, are there rules for them in the book? For an initial release I do not plan to support things which are not explicitly defined in the book

**Comment by RGK13** [comment]
> As far as I can tell, there is no difference between the character sheets for PCs and NPCs, hence why there is no choice on character creation.
> 
> I can see why it would still be helpful to distinguish between the two, though, for organization purposes and macros, to name a few.
> 
> As far as vehicles go, are there rules for them in the book? For an initial release I do not plan to support things which are not explicitly defined in the book

Totally understand about the first version and the vehicles but know thats it's going to come up at some point... As for the PC and NPC's, I dont know if it's a lot of work to implement but I'm pretty sure that it,s going to affect game play since Foundry uses the difference at it's core so just want to make sure your are covered from the start.

**Comment by jalensailin** [comment]
I don't think Foundry actually does use the difference at its core. The example that I know of, is for Rolling NPC Initiative. However, this doesn't differentiate between actor types, it determines NPCs by looking at ownership, i.e. non-player-owned combatants. Do you have other examples? The reason I ask is because there is no default NPC actor-type in foundry, so foundry would have no way of knowing what an NPC vs a PC is just by actor-type.

All that being said, it's pretty easy to implement a 2nd actor type, which uses the same logic/sheets. Any ideas what it should be called? Right now, the default actor is called a "Super". My inclination was to make NPCs called "Villain" but that might be a misnomer since you can have "hero" NPCs. I could just call them "NPC" but that seems boring lol

**Comment by RGK13** [comment]
No idea...I'm just like a deer in the headlights now...

**Comment by jalensailin** [comment]
haha no problem. ill ruminate on it, or if anyone else has any ideas, feel free to let me know

**Comment by jalensailin** [comment]
I've settled on just calling them NPCs. This has been added in the most recent update. Note, there is currently no functional difference between "NPC" actors and "Super" actors.
