### ISSUE TITLE
Damage Multiplier setting to Ability not rank

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#18]
When I made a new character adding points to an ability changes the damage multiplier on the sheet but not in the roll calculations.
![image](https://github.com/jalensailin/mvrpg/assets/84296981/ce483289-f5e5-44d3-9505-1201fe256c91)

**Comment by jalensailin** [comment]
Oops, that's what happens when you code late at night after a long day! This should again be addressed in the most recent update! Let me know in this thread if there are still issues related to this problem. By the way, in the future you can comment on the old/closed issues (in this case it was issue #7) to tell me there is still a problem, and I can reopen the issue. that way it's easier to keep the same problem tracked in one place. Not a big deal at all though :). And thank you for testing!
