### ISSUE TITLE
Add attribute for damage modifier

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#7]
Since there are a number of things that modify the Ability modifier for damage without affecting the ability itself maybe that should be an attribute.  For example Attack Stance doubles the Ability modifier to Melee damage.  I can set up an effect to increase the Melee value but there's no way to bump just the additional damage.

**Comment by jalensailin** [comment]
You're right. Thanks for bringing this up. I'll add the data-point

**Comment by jalensailin** [comment]
This should be addressed in the most recent update. Note, the new data point controls a *bonus* to the damage modifier, not the damage modifier itself. This is because the value of the damage modifier is dependent on the value of the ability itself, and is thus calculated dynamically in the following way: `ability-score + ability-damage-modifier-bonus`. Thus, if you want to do something like double an actor's effective damage modifier, you would have to add the value of the ability score once more. See the attached screenshot. 

![image](https://github.com/jalensailin/mvrpg/assets/72114365/ebb0ba7a-c617-4a37-9a34-181863f5fa92)
